remote_theme: chrisrhymes/bulma-clean-theme
permalink: pretty
defaults:
  -
    scope:
      path: ""
    values:
      menubar: menu
      show_navbar: false
      show_sidebar: false
      show_hero: false